{% set version = "0.8-90" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-foreign
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/foreign_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/foreign/foreign_{{ version }}.tar.gz
  sha256: 1dc6798002a50b9014227a2d20c0c2450fe6feb991a4a0b3bee36c0ee779a196

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('foreign')"           # [not win]
    - "\"%R%\" -e \"library('foreign')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=foreign
  license: GPL-2.0-or-later
  summary: Reading and writing data stored by some versions of 'Epi Info', 'Minitab', 'S', 'SAS', 'SPSS', 'Stata', 'Systat', 'Weka', and for reading and writing some 'dBase' files.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
